### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by yongming9011** [liyanxi/BadgeView#2]
若未RadioGroup里面的RadioButton添加徽章的话，点击该RadioButton后会导致其一直处于选中状态，导致点击其他RadioButton后上述的控件还是处于选中状态。
代码如下：
BadgeTextView badgeTextView = new BadgeTextView(this);
        badgeTextView.setTargetView(rbHome);
        badgeTextView.setBadgeCount(2);
        badgeTextView.setmDefaultRightPadding(30);

**Comment by liyanxi** [comment]
目前不支持该功能，这个BadgeTextView只是单纯的添加徽章标记，实际的显示与隐藏还是需要自己控制，
badgeTextView.setBadgeShown(bool)
